### ISSUE TITLE
[PE-D] February 30th as a appointment date does not throw error message.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-2/tp#237]
When entering `appt-b 1 time/2023-02-30-12-12` to add an appointment, February 30th is never a possible date but is shows successful message. 
The current way of this application to deal with this issue is to add February 30th as February 28th. But no error message is shown so the user would not be aware of the situation.

![Screen Shot 2022-04-01 at 15.05.35.png](https://raw.githubusercontent.com/xpzmichael/ped/main/files/3f81b6cb-cc13-44a1-8b6f-05b0946f10dd.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: xpzmichael/ped#5

**Comment by WJunHong** [comment]
Need to add 1 more check for feb 28 & leap years

**Comment by cwnm** [comment]
https://github.com/AY2122S2-CS2103T-W13-1/tp
-Working check for dates
