### ISSUE TITLE
[PE-D] UserGuide markdown issue

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-2/tp#246]
![Screen Shot 2022-04-01 at 15.47.44.png](https://raw.githubusercontent.com/xpzmichael/ped/main/files/8d0e8945-d1d6-48da-9290-cf2a96560b04.png)

`**Caution**` should be **`Caution`** instead.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: xpzmichael/ped#10

**Comment by janald99** [comment]
This was fixed days before the mock PE i believe.
