### ISSUE TITLE
[PE-D] People with same name are not allowed

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-2/tp#247]
![Screen Shot 2022-04-01 at 15.50.28.png](https://raw.githubusercontent.com/xpzmichael/ped/main/files/38b29575-7012-4ad3-bea0-45b9c4745bde.png)

People can have same name but should not have same number. However, it is completely the opposite right now. People with same phone number are allowed, but people with same name are not allowed.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: xpzmichael/ped#11

**Comment by janald99** [comment]
name not allowed to be the same as the user wants to differentiate clients by their names, this will be better for them to give everyone unique names. clients can have the same number as they may share the same house phone, office phone, estate number etc..
